import { createStitches } from '@stitches/react';

const baseColors = {
  primary: '#454dcc',
  primary600: '#363EBF',
  primary700: '#2D35B6',
  black: '#000000',
  white: '#FFFFFF',
  offWhite: 'rgba(207, 220, 237, 0.5)',
  darkBase: '#263238',
  darkDetail: '#444751',
  background: '#F8F9FF',
  greyLight: '#DFEAF8',
  greyBase: '#6A728F',
  greyDetail: '#CFDCED',
  halfPurple: 'rgba(69, 77, 204,0.5)',
  success: '#30C78C',
  danger: '#ED2E7E',
  warning: '#D1AE33',
  alert: '#FDCB6E',
  pending: '#10CEE4',
  salmon100: '#FCE3D9',
  salmon400: '#E6A286',
  dangerBackground: '#DC345CA1',
  opaqueWhiteHover: '#575ED1',
  opaqueWhiteActive: '#696FD6',
  inputColor: '#838383',
  darkBlueMagenta: '#6D6AEE',
  tertiary500: '#f6f6f6f6',
  tertiary600: '#E5E5E5',
  tertiary700: '#DBDBDB',
  lavender: '#E8E9F9',
};

export const colors = {
  ...baseColors,
  text: baseColors.darkBase,
  header: baseColors.darkBase,
  disabled: baseColors.greyBase,
  border: baseColors.greyLight,
  menuBackgroundHover: baseColors.opaqueWhiteHover,
  menuBackgroundActive: baseColors.opaqueWhiteActive,
  inputBorder: baseColors.inputColor,
  inputText: baseColors.inputColor,
  placeholderText: baseColors.greyBase,
};

export const fontSizes = {
  h2: '24px',
  h3: '18px',
  link: '14px',
  label: '12px',
  body: '16px',
  input: '14px',
  detail: '14px',
  small: '12px',
  xs: '10px',
  tiny: '8px',
};

export const { styled, css, globalCss, keyframes, getCssText } = createStitches(
  {
    prefix: 'sibi',
    media: {
      tablet: '(min-width: 575px)',
      desktop: '(min-width: 990px)',
    },
    utils: {
      stackGap: (value: string) => ({
        $$gap: `${value}`,
      }),
      size: (value: string) => ({
        width: value,
        height: value,
      }),
    },
    theme: {
      colors: {
        primary: colors.primary,
        primary600: colors.primary600,
        primary700: colors.primary700,
        black: colors.black,
        white: colors.white,
        darkBase: colors.darkBase,
        darkDetail: colors.darkDetail,
        background: colors.background,
        greyLight: colors.greyLight,
        greyBase: colors.greyBase,
        greyDetail: colors.greyDetail,
        header: colors.header,
        success: colors.success,
        danger: colors.danger,
        warning: colors.warning,
        alert: colors.alert,
        pending: colors.pending,
        salmon100: colors.salmon100,
        border: colors.border,
        focusBorder: colors.halfPurple,
        placeholder: colors.greyBase,
        text: colors.text,
        disabled: colors.disabled,
        menuBackgroundHover: colors.menuBackgroundHover,
        menuBackgroundActive: colors.menuBackgroundActive,
        inputBorder: colors.inputBorder,
        inputText: colors.inputText,
        placeholderText: colors.placeholderText,
        darkBlueMagenta: colors.darkBlueMagenta,
        tertiary500: colors.tertiary500,
        tertiary600: colors.tertiary600,
        tertiary700: colors.tertiary700,
        lavender: colors.lavender,
      },
      fontSizes,
      fontWeights: {
        lightWeight: '300',
        normal: '400',
        medium: '500',
        semiBold: '600',
        bold: '700',
        extraBold: '800',
      },
      fonts: {
        base: '"Nunito Sans"',
      },
      shadows: {
        xs: '0px 1px 3px rgba(0, 0, 0, 0.03), 0px 2px 4px rgba(0, 0, 0, 0.02);',
        small:
          '0px 1px 4px rgba(0, 0, 0, 0.03), 0px 3px 6px rgba(0, 0, 0, 0.04);',
        large:
          '0px 2px 8px rgba(0, 0, 0, 0.08), 0px 10px 20px rgba(0, 0, 0, 0.04)',
      },
    },
  },
);
